//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GameAppWindowWidth {
            get {
                return ((double)(this["GameAppWindowWidth"]));
            }
            set {
                this["GameAppWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GameAppWindowHeight {
            get {
                return ((double)(this["GameAppWindowHeight"]));
            }
            set {
                this["GameAppWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GameAppWindowTop {
            get {
                return ((double)(this["GameAppWindowTop"]));
            }
            set {
                this["GameAppWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double GameAppWindowLeft {
            get {
                return ((double)(this["GameAppWindowLeft"]));
            }
            set {
                this["GameAppWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AllWhiteWindowWidth {
            get {
                return ((double)(this["AllWhiteWindowWidth"]));
            }
            set {
                this["AllWhiteWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AllWhiteWindowHeight {
            get {
                return ((double)(this["AllWhiteWindowHeight"]));
            }
            set {
                this["AllWhiteWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AllWhiteWindowTop {
            get {
                return ((double)(this["AllWhiteWindowTop"]));
            }
            set {
                this["AllWhiteWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AllWhiteWindowLeft {
            get {
                return ((double)(this["AllWhiteWindowLeft"]));
            }
            set {
                this["AllWhiteWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlideGameWindowWidth {
            get {
                return ((double)(this["SlideGameWindowWidth"]));
            }
            set {
                this["SlideGameWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlideGameWindowHeight {
            get {
                return ((double)(this["SlideGameWindowHeight"]));
            }
            set {
                this["SlideGameWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlideGameWindowTop {
            get {
                return ((double)(this["SlideGameWindowTop"]));
            }
            set {
                this["SlideGameWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SlideGameWindowLeft {
            get {
                return ((double)(this["SlideGameWindowLeft"]));
            }
            set {
                this["SlideGameWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SudokuWindowWidth {
            get {
                return ((double)(this["SudokuWindowWidth"]));
            }
            set {
                this["SudokuWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SudokuWindowHeight {
            get {
                return ((double)(this["SudokuWindowHeight"]));
            }
            set {
                this["SudokuWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SudokuWindowTop {
            get {
                return ((double)(this["SudokuWindowTop"]));
            }
            set {
                this["SudokuWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double SudokuWindowLeft {
            get {
                return ((double)(this["SudokuWindowLeft"]));
            }
            set {
                this["SudokuWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FixPosColor {
            get {
                return ((int)(this["FixPosColor"]));
            }
            set {
                this["FixPosColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RubikCubeWindowWidth {
            get {
                return ((double)(this["RubikCubeWindowWidth"]));
            }
            set {
                this["RubikCubeWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RubikCubeWindowHeight {
            get {
                return ((double)(this["RubikCubeWindowHeight"]));
            }
            set {
                this["RubikCubeWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RubikCubeWindowTop {
            get {
                return ((double)(this["RubikCubeWindowTop"]));
            }
            set {
                this["RubikCubeWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double RubikCubeWindowLeft {
            get {
                return ((double)(this["RubikCubeWindowLeft"]));
            }
            set {
                this["RubikCubeWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LifeGameWindowWidth {
            get {
                return ((double)(this["LifeGameWindowWidth"]));
            }
            set {
                this["LifeGameWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LifeGameWindowHeight {
            get {
                return ((double)(this["LifeGameWindowHeight"]));
            }
            set {
                this["LifeGameWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LifeGameWindowTop {
            get {
                return ((double)(this["LifeGameWindowTop"]));
            }
            set {
                this["LifeGameWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LifeGameWindowLeft {
            get {
                return ((double)(this["LifeGameWindowLeft"]));
            }
            set {
                this["LifeGameWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BlockGameWindowWidth {
            get {
                return ((double)(this["BlockGameWindowWidth"]));
            }
            set {
                this["BlockGameWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BlockGameWindowHeight {
            get {
                return ((double)(this["BlockGameWindowHeight"]));
            }
            set {
                this["BlockGameWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BlockGameWindowTop {
            get {
                return ((double)(this["BlockGameWindowTop"]));
            }
            set {
                this["BlockGameWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BlockGameWindowLeft {
            get {
                return ((double)(this["BlockGameWindowLeft"]));
            }
            set {
                this["BlockGameWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TetrisWindowWidth {
            get {
                return ((double)(this["TetrisWindowWidth"]));
            }
            set {
                this["TetrisWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TetrisWindowHeight {
            get {
                return ((double)(this["TetrisWindowHeight"]));
            }
            set {
                this["TetrisWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TetrisWindowTop {
            get {
                return ((double)(this["TetrisWindowTop"]));
            }
            set {
                this["TetrisWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TetrisWindowLeft {
            get {
                return ((double)(this["TetrisWindowLeft"]));
            }
            set {
                this["TetrisWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MineSweeperTop {
            get {
                return ((double)(this["MineSweeperTop"]));
            }
            set {
                this["MineSweeperTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MineSweeperLeft {
            get {
                return ((double)(this["MineSweeperLeft"]));
            }
            set {
                this["MineSweeperLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MineSweeperWidth {
            get {
                return ((double)(this["MineSweeperWidth"]));
            }
            set {
                this["MineSweeperWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MineSweeperHeight {
            get {
                return ((double)(this["MineSweeperHeight"]));
            }
            set {
                this["MineSweeperHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int MineSweeperRow {
            get {
                return ((int)(this["MineSweeperRow"]));
            }
            set {
                this["MineSweeperRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int MineSweeperCol {
            get {
                return ((int)(this["MineSweeperCol"]));
            }
            set {
                this["MineSweeperCol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MineSweeperBomb {
            get {
                return ((int)(this["MineSweeperBomb"]));
            }
            set {
                this["MineSweeperBomb"] = value;
            }
        }
    }
}
